credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      first_name: John
      last_name: Smith
      logged_in: True
      password: abc
cookie:
  name: some_cookie_name
  key: some_signature_key  # Chave para assinar o cookie
  expiry_days: 30
pre-authorized: # Optional
  emails:
  - melsby@gmail.com
