credentials:
  usernames:
    johndoe:
      email: johndoe@gmail.com
      name: John Doe
      password: "123"  # A senha será hasheada automaticamente
    janedoe:
      email: janedoe@gmail.com
      name: Jane Doe
      password: "456"  # A senha será hasheada automaticamente
cookie:
  name: some_cookie_name
  key: some_signature_key  # Chave para assinar o cookie
  expiry_days: 30

