name: Daily ETL Process

on:
  schedule:
    # Executa todo dia às meio dia e 18 horas
    - cron: '0 15,21 * * *' 
  workflow_dispatch:  # Permite execução manual
  repository_dispatch:
    types:
      - trigger_daily_etl

jobs:
  run-etl:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Atualizado para v3
        
      - name: Set up Python
        uses: actions/setup-python@v4  # Atualizado para v4
        with:
          python-version: '3.11'  # Especificando uma versão exata do Python
          cache: 'pip'  # Habilitando cache de dependências
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Recomendado usar requirements.txt
          
      - name: Run ETL script
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: python portfolio_etl.py
        
      - name: Handle failures
        if: failure()
        run: |
          echo "O processo ETL falhou. Verificando logs..."
          
