name: Daily ETL Process

on:
  schedule:
    # Executa todo dia às 10:00 UTC
    - cron: '0 10 * * *'
  workflow_dispatch:  # Permite execução manual através da interface do GitHub

jobs:
  run-etl:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas yfinance pymongo
    
    - name: Run ETL script
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
      run: |
        python portfolio_etl.py
